export enum Report {
    DNSCOMPRO = 'DNS Compromise',
    DNSPOISON = 'DNS Poisoning',
    DDOSA = 'DDoS Attack',
    FTPB = 'FTP Brute-Force',
    PINGOFDEATH = 'Ping of Death',
    PHISHING = 'Phishing',
    FRAUDVOIP = 'Fraud VoIP',
    OPENPROXY = 'Open Proxy',
    WEBSPAM = 'Web Spam',
    EMAILSPAM = 'Email Spam',
    BLOGSPAM = 'Blog Spam',
    VPNIP = 'VPN IP',
    HACKING = '	Hacking',
    SQLINJECION  = 'SQL Injection',
    SPOOFING = 'Spoofing',
    BRUTEFORCE = 'Brute-Force',
    BADWEBBOT = 'Bad Web Bot',
    EXPLOITEDHOST = 'Exploited Host',
    WEBAPPATTACK = 'Web App Attack',
    SSH = 'SSH',
    IOTTARGETD = 'IoT Targeted',
  }
  